FleetPride.BidManager/Controllers/VendorGradeController.cs
using FleetPride.BidManager.Models;
using FleetPride.BidManager.Repository;
using FleetPride.BidManager.Utilities;
using FleetPride.Excel;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FleetPride.BidManager.Controllers
{
    public class VendorGradeController : Controller
    {
        protected Utilities.Logger logger = new Utilities.Logger();
        IAuthorizationRepository _userInfoRepository;
        IVendorGradeRepository _vendorGradeRepository;
        IExcelHelper _excelHelper;

        /// <summary>  
        ///  Class Default constructor for instantiating the Repository Interfaces.
        /// </summary>
        public VendorGradeController(IAuthorizationRepository userInfoRepository, IExcelHelper excelHelper, IVendorGradeRepository vendorGradeRepository)
        {
            _userInfoRepository = userInfoRepository;
            _excelHelper = excelHelper;
            _vendorGradeRepository = vendorGradeRepository;
        }

        /// <summary>
        /// Index default action method
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.VendorGrade))
            {
                ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                return View();
            }
            else
            {
                return RedirectToAction("Index", "CrossEntry");
            }
        }

        /// <summary>
        /// get all vendor grades
        /// </summary>
        /// <returns></returns>
        public JsonResult GetVendorGrades()
        {
            var vendorGaresList = _vendorGradeRepository.GetVendorGrades();

            return new JsonResult()
            {
                Data = vendorGaresList,
                MaxJsonLength = Int32.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        /// <summary>
        /// Upload Vendor Grade File
        /// </summary>
        /// <returns></returns>
        public JsonResult UploadVendorGradeFile()
        {
            return UploadVendorGradeData<VendorGradeEntity>();
        }

        /// <summary>
        /// Upload Vendor Grade File Data
        /// </summary>
        /// <typeparam name="ModelType"></typeparam>
        /// <returns></returns>
        protected JsonResult UploadVendorGradeData<ModelType>() where ModelType : class
        {
            int errorCount = 0;
            if (Request.Files.Count == 1)
            {
                try
                {
                    //save the uploaded file to the App_Data folder
                    string fileName = "~/App_Data/VendorGrade_UploadFile_" + System.Web.HttpContext.Current.User.Identity.Name + "_" + DateTime.Now.ToString("MM-dd-yyyy HH.mm.ss") + ".xls";
                    Request.Files[0].SaveAs(Server.MapPath(fileName));

                    using (var package = new ExcelPackage(new System.IO.FileInfo(Server.MapPath(fileName))))
                    {
                        //read the data from the excel sheet
                        var workSheet = package.Workbook.Worksheets.First();
                        List<ModelType> records = workSheet.GetRecords<ModelType>();

                        //execute the data annotation based validations
                        GenericValidator.TryValidate(records);

                        //count the failed records
                        errorCount = records.Where(x => !((x as BaseExcelModel).IsValid)).Count();

                        //if there are some failed records then create a sheet in the original file with the status and error messages.
                        if (errorCount > 0)
                        {
                            ExcelWorksheet resultSheet = package.Workbook.Worksheets.AddOrReplace("Upload Result");
                            resultSheet.Cells["A1"].LoadFromCollection<ModelType>(records, true);
                            package.Save();
                        }

                        //save all the valid records to session
                        Session["ValidVendorGradeData"] = null;
                        Session["ValidVendorGradeData"] = records.FindAll(x => (x as BaseExcelModel).IsValid);
                        SaveValidVendorGradeData(Session["ValidVendorGradeData"] as List<VendorGradeEntity>);
                    }

                    return Json(new { error = false, totalError = errorCount, uploadStatus = (errorCount == 0), path = fileName });
                }
                catch (System.Reflection.TargetInvocationException ex)
                {
                    //ExceptionManager.LogExceptionDetails(ex);
                    logger.Exception(ex);
                    string msg = ex.Message;
                    if (ex.InnerException != null)
                        msg = ex.InnerException.Message;

                    return Json(new { errorText = msg, error = true, uploadStatus = false });
                }
                catch (Exception ex)
                {
                    logger.Exception(ex);
                    return Json(new { errorText = ex.Message, error = true, uploadStatus = false });
                }
            }

            return Json(new { error = true, uploadStatus = false });
        }

        /// <summary>
        /// Save valid records of vendor grade in bulk
        /// </summary>
        /// <param name="records"></param>
        private void SaveValidVendorGradeData(List<VendorGradeEntity> records)
        {
            _vendorGradeRepository.BulkSaveVendorGrades(records, System.Web.HttpContext.Current.User.Identity.Name);
        }

        /// <summary>
        /// Method to download the uploaded vendor grade excel of errors
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        public ActionResult DownloadVendorGradeErrorDataFile(string fileName)
        {
            return File(Server.MapPath(fileName), "excel", "VendorGrade_ErrorFile.xlsx");
        }
    }
}

FleetPride.BidManager/Views/VendorGrade/Index.cshtml
@using FleetPride.BidManager.Utilities;
@{
    ViewBag.Title = "Vendor Grade";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .dx-fileuploader-input-container {
        display: none !important;
    }

    .dx-fileuploader-button {
        background-color: #00a65a;
        color: white;
        padding: 0px;
    }

        .dx-fileuploader-button:hover {
            background-color: #008D4C !important;
            color: white;
        }

    .dx-group-panel-message {
        color: black !important;
    }

    #fileUploader .dx-button-content {
        height: 33px;
        width: 90px;
        padding-left: 0px;
        padding-top: 3px;
        font-size: 13px;
    }

    .dx-button .dx-state-hover {
        background-color: #008D4C !important;
    }

    /*#buttonsright .dx-button.dx-state-focused {
        background-color: #00a65a !important;
        border-color: #00a65a !important;
    }*/

    .editable {
        background-color: rgba(255, 255, 0, 0.25) !important;
    }

    .red {
        background-color: #ff471a !important;
    }

    .green {
        background-color: #ffff33 !important;
    }

    .yellow {
        background-color: #00e600 !important;
    }

    .marginRight {
        margin-right: 50px !important;
    }

    .dx-button-text {
        padding-top: 3px !important;
    }

    .dx-button .dx-state-hover {
        background-color: #51a351 !important;
    }

    /*#buttonsright .dx-button.dx-state-focused {
        background-color: #00a65a;
        border-color: #008d4c;
    }*/

    .dx-datagrid-export-button .dx-icon-export-to:before {
        content: "\f05f ";
    }
</style>

<div class="content-wrapper">
    <div class="container" style="width:auto !important">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1 style="float:left;">
                Vendor Grade
            </h1>
            <div style="height: 35px;float: right;margin-top: 0px; margin-bottom: 10px !important;" id="buttonsright">
                <div id="fileUploader" style="display:inline-block;width:105px; height: 62px;padding: 0px; margin-top:-13px;border:solid 0px black;float: right;"></div>
            </div>
            <br /><br />
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="box box-default" id="box">
                <div class="box-body">
                    <div id="gridContainer"></div>
                </div>
            </div>
            <!-- /.box -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.container -->
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#nav_menu li").removeClass("active");
        $('#VendorGrade').addClass('active');
        $("#box").hide();
        var dataGrid;
        LoadVendorGradeList();
    });

    $("#fileUploader").dxFileUploader({
        accept: ".xls,.xlsx",
        labelText: '',
        selectButtonText: 'Upload',
        uploadMode: 'instantly',
        uploadUrl: '@Url.Action("UploadVendorGradeFile", "VendorGrade")',
        showFileList: false,
        onUploadStarted: function () {
            $("#spinner").show();
        },
        onUploaded: function (e) {
            var uploadResponse = JSON.parse(e.jQueryEvent.target.responseText)
            if (uploadResponse.error) {
                DevExpress.ui.dialog.alert('Error occurred, please try again.</br>' + 'Error Message : ' + uploadResponse.errorText, 'Message');
                $("#spinner").hide();
            }
            else {
                if (uploadResponse.totalError == 0) {
                    DevExpress.ui.notify("File uploaded successfully, all data uploaded.", "success", 3000);
                    $("#spinner").hide();
                    LoadVendorGradeList();
                }
                else {
                    DevExpress.ui.dialog.alert('There were some record(s) which were not uploaded due to error(s).<br/>' + 'Total number of error(s) : ' + uploadResponse.totalError + '<br/> Please check downloaded excel sheet for error details, correct the error(s) and upload the excel again.', 'Message');
                    window.location = '@Url.Action("DownloadVendorGradeErrorDataFile", "VendorGrade")?fileName=' + uploadResponse.path;
                    $("#spinner").hide();
                    LoadVendorGradeList();
                }
            }
            e.component.reset();
        }
    });

    function LoadVendorGradeList() {
        $("#box").show();
        $("#spinner").show();
        $.ajax({
            url: "@Url.Action("GetVendorGrades", "VendorGrade")",
            type: 'GET',
            contentType: 'application/json; charset=utf-8',
            success: function (VendorGradeData) {
                $("#spinner").hide();
                dataGrid = $("#gridContainer").dxDataGrid({
                    dataSource: VendorGradeData,
                    paging: {
                        pageSize: 50
                    },
                    height: function () {
                        return dynamicheight = $(document).height() - 190;
                    },
                    pager: {
                        showPageSizeSelector: true,
                        allowedPageSizes: [10, 50, 100, 200, 500],
                        showInfo: true
                    },
                    "export": {
                        enabled: true,
                        fileName: "VendorGrade_List" + "_" + '@DateTime.Now.ToString("MM/dd/yyyy HH:mm:ss")',
                    },
                    filterRow: {
                        visible: true,
                        applyFilter: "auto"
                    },
                    headerFilter: {
                        visible: true
                    },
                    scrolling: {
                        showScrollbar: 'always'
                    },
                    columnChooser: {
                        enabled: true,
                        height: 360,
                        width: 250,
                        mode: "select",
                        emptyPanelText: 'Place to hide the columns.'
                    },
                    hoverStateEnabled: true,
                    allowColumnResizing: true,
                    columnAutoWidth: true,
                    showBorders: true,
                    showColumnLines: true,
                    showRowLines: true,
                    columns: [
                        { dataField: "VendorGradeId", caption: "Vendor Grade Id", visible: false, allowEditing: false, showInColumnChooser: false },
                        { dataField: "Category", caption: "Category", allowEditing: true, visible: true },
                        { dataField: 'VendorNumber', caption: "Vendor Number", allowEditing: true, visible: true },
                        { dataField: 'VendorName', caption: "Vendor Name", wordWrapEnabled: true, allowEditing: true, visible: true },
                        { dataField: "ColorCode", caption: "Color Code", allowEditing: true, visible: true },
                        { dataField: "Color", caption: "Color", allowEditing: true, visible: true },
                        { dataField: "Definition", caption: "Definition", allowEditing: true, visible: true },
                        { dataField: "LastModifiedBy", caption: "Modified By", allowEditing: false, visible: false, showInColumnChooser: true },
                        { dataField: "LastModifiedOn", caption: "Modified Date", dataType: 'date', allowEditing: false, visible: false, showInColumnChooser: true }
                    ],
                    onCellPrepared: function (e) {
                        if (e.rowType == "header" || e.rowType === "data") {
                            e.cellElement.addClass('moveToCenter');
                        }
                    },
                });
                $('.dx-icon-export-excel-button').removeClass('dx-icon-export-excel-button').addClass('fa fa-fw fa-download');
            }
        });
    }
</script>