FleetPride.BidManager/Controllers/SummaryController.cs
using FleetPride.BidManager.Repository;
using FleetPride.BidManager.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FleetPride.BidManager.Controllers
{
    public class SummaryController : Controller
    {
        IAuthorizationRepository _userInfoRepository;
        ISummaryRepository _summaryRepository;

        /// <summary>  
        ///  Class Default constructor for instantiating the Repository Interfaces.
        /// </summary>
        public SummaryController(IAuthorizationRepository userInfoRepository, ISummaryRepository summaryRepository)
        {
            _userInfoRepository = userInfoRepository;
            _summaryRepository = summaryRepository;
        }

        /// <summary>
        /// CrowdsourcingSummary action method
        /// </summary>
        /// <returns></returns>
        public ActionResult CrowdsourcingSummary()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.CrowdsourcingSummary))
            {
                ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                return View();
            }
            else
            {
                return RedirectToAction("Index", "CrossEntry");
            }
        }

        /// <summary>
        /// BidReviewSummary action method
        /// </summary>
        /// <returns></returns>
        public ActionResult ProgressSummary()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.ProgressSummary))
            {
                ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                return View();
            }
            else
            {
                return RedirectToAction("Index", "CrossEntry");
            }
        }

        public JsonResult GetCrowdsourcingSummary()
        {
            var crowdsourcingSummaryList = _summaryRepository.GetCrowdsourcingSummary(_userInfoRepository.GetAuthorisedUserRole(), System.Web.HttpContext.Current.User.Identity.Name);
            return new JsonResult()
            {
                Data = crowdsourcingSummaryList,
                MaxJsonLength = Int32.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult GetProgressSummary()
        {
            var progressSummaryList = _summaryRepository.GetProgressSummary(_userInfoRepository.GetAuthorisedUserRole(), System.Web.HttpContext.Current.User.Identity.Name);
            return new JsonResult()
            {
                Data = progressSummaryList,
                MaxJsonLength = Int32.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
    }
}

FleetPride.BidManager/Views/Summary/CrowdsourcingSummary.cshtml
@using FleetPride.BidManager.Utilities;
@{
    ViewBag.Title = "Crowdsourcing Summary";
}


<div class="content-wrapper">
    <div class="container" style="width:auto !important">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Crowdsourcing Summary
            </h1>
            <br />
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="box box-default">
                <div class="box-body">
                    <div id="gridContainer"></div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.container -->
</div>
<!-- /.content-wrapper -->
<script type="text/javascript">

    $(document).ready(function () {
        $("#nav_menu li").removeClass("active");
        $('#crowdsourcing').addClass('active');
        $('#CrowdsourcingSummary').addClass('active');
        GetCrowdsourcingSummary();
    });

    function CloseBid(s) {
        var result = DevExpress.ui.dialog.confirm("Do you want to pull the bid from Crowdsourcing?", "Confirm");
        result.done(function (dialogResult) {
            if (dialogResult) {
                $("#spinner").show();
                $.ajax({
                    url: "@Url.Action("UpdateBidStatus", "CrossReport")",
                    type: 'POST',
                    data: JSON.stringify({
                        BidId: s.currentTarget.getAttribute('BidId'), bidName: s.currentTarget.getAttribute('BidName'), status: '@Constants.CrossFinalization'
                    }),
                    contentType: 'application/json; charset=utf-8',
                    success: function (result) {
                        $("#spinner").hide();
                        DevExpress.ui.notify("Bid pulled from Crowdsourcing successfully. Please go to Cross Report for CrossFinalization of this bid.", "success", 5000);
                        GetCrowdsourcingSummary();
                    }
                });
            }
        });
    }

    function GetCrowdsourcingSummary() {
        $.ajax({
            url: "@Url.Action("GetCrowdsourcingSummary", "Summary")",
            type: 'GET',
        contentType: 'application/json; charset=utf-8',
        success: function (bidSummary) {
            $("#gridContainer").dxDataGrid({
                dataSource: bidSummary,
                paging: {
                    pageSize: 50
                },
                height: function () {
                    return dynamicheight = $(document).height() - 195;
                },
                pager: {
                    showPageSizeSelector: true,
                    allowedPageSizes: [10, 50, 100, 200, 500],
                    showInfo: true
                },
                editing: {
                    mode: "row",
                    allowUpdating: false,
                    allowDeleting: false,
                    allowAdding: false,
                    texts: {
                        addRow: 'Add new record'
                    }
                },
                filterRow: {
                    visible: true,
                    applyFilter: "auto"
                },
                headerFilter: {
                    visible: true
                },
                selection: {
                    mode: "single"
                },
                scrolling: {
                    showScrollbar: 'always'
                },
                columnChooser: {
                    enabled: true,
                    height: 360,
                    width: 250,
                    mode: "select",
                    emptyPanelText: 'Place to hide the columns.'
                },
                hoverStateEnabled: true,
                allowColumnResizing: true,
                columnAutoWidth: true,
                showBorders: true,
                showColumnLines: true,
                showRowLines: true,
                onCellPrepared: function (e) {
                    if (e.rowType == "header" || e.rowType === "data") {
                        e.cellElement.addClass('moveToCenter');
                    }
                },
                columns: [
                     {
                         dataField: '',
                         headerCellTemplate: function (header, info) {
                             $("<div>").html("<center>Pull Bid From <br/>Crowdsourcing</center>").appendTo(header);
                         },
                         allowEditing: false,
                         visible: true,
                         showInColumnChooser: false,
                         cellTemplate: function (container, options) {
                             if (options.data.BidStatus == '@Constants.CrowdSourcing') {
                                 $("<a>", { "BidId": options.data.BidId, "BidName": options.data.BidName }).click(function (s) { CloseBid(s) })
                                .append($("<span>", { "title": "Pull bid from Crowdsourcing, It will move the bid to CrossFinalization." }).addClass('fa fa-fw fa-check fa-lg'))
                                .appendTo(container);

                             }
                             else {
                                 $("<a>").css('opacity', '0.4')
                              .append($("<span>", { "title": "Bid is not in Crowdsourcing." }).addClass('fa fa-fw fa-check fa-lg'))
                              .appendTo(container);
                             }

                         }
                     },
                    { dataField: "BidName", caption: "Bid Name", wordWrapEnabled: true, visible: true },
                    { dataField: "BidType", caption: "Bid Type", wordWrapEnabled: true, visible: true },
                    { dataField: "Rank", caption: "Bid Rank", visible: true, dataType: 'number' },
                    { dataField: 'DueDate', caption: 'Due Date', visible: false, showInColumnChooser: false, dataType: 'date' },
                    { dataField: "BidStatus", caption: "Bid Status", wordWrapEnabled: true, visible: true },
                    {
                        dataField: 'UploadPartCount', caption: "Uploaded Parts Count", visible: true, dataType: 'number',
                        headerCellTemplate: function (header, info) {
                            $("<div>").html("<center>Uploaded<br/>Parts Count</center>").appendTo(header);
                        }
                    },
                    {
                        dataField: 'CrowdSourcingPartCount', caption: "Crowdsourcing Parts Count", visible: true, dataType: 'number',
                        headerCellTemplate: function (header, info) {
                            $("<div>").html("<center>Crowd Sourcing<br/>Parts Count</center>").appendTo(header);
                        }
                    },
                    {
                        dataField: 'UserSubmittedPartCount', caption: "Submitted Parts", visible: true, dataType: 'number',
                        headerCellTemplate: function (header, info) {
                            $("<div>").html("<center>Submitted<br/>Parts</center>").appendTo(header);
                        }
                    },
                    {
                        dataField: 'ValidatedPartCount', caption: "Validated Parts", visible: true, dataType: 'number',
                        headerCellTemplate: function (header, info) {
                            $("<div>").html("<center>Validated<br/>Parts</center>").appendTo(header);
                        }
                    },
                ],
            });
        }
    });
    }

  
</script>

FleetPride.BidManager/Views/Summary/ProgressSummary.cshtml
@using FleetPride.BidManager.Utilities;
@{
    ViewBag.Title = "ProgressSummary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <div class="container" style="width:auto !important">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Progress Summary
            </h1>
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="box box-default">
                <div class="box-body">
                    <div id="gridContainer"></div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.container -->
</div>
<!-- /.content-wrapper -->
<script type="text/javascript">
    $(document).ready(function () {
        $("#nav_menu li").removeClass("active");
        $('#Bids').addClass('active');
        $('#ProgressSummary').addClass('active');
        $.ajax({
            url: "@Url.Action("GetProgressSummary", "Summary")",
            type: 'GET',
            contentType: 'application/json; charset=utf-8',
            success: function (progressSummary) {
                $("#gridContainer").dxDataGrid({
                    dataSource: progressSummary,
                    paging: {
                        pageSize: 50
                    },
                    height: function () {
                        return dynamicheight = $(document).height() - 175;
                    },
                    pager: {
                        showPageSizeSelector: true,
                        allowedPageSizes: [10, 50, 100, 200, 500],
                        showInfo: true
                    },
                    filterRow: {
                        visible: true,
                        applyFilter: "auto"
                    },
                    headerFilter: {
                        visible: true
                    },
                    scrolling: {
                        showScrollbar: 'always'
                    },
                    columnChooser: {
                        enabled: true,
                        height: 360,
                        width: 250,
                        mode: "select",
                        emptyPanelText: 'Place to hide the columns.'
                    },
                    hoverStateEnabled: true,
                    allowColumnResizing: true,
                    columnAutoWidth: true,
                    showBorders: true,
                    showColumnLines: true,
                    showRowLines: true,
                    allowColumnReordering: true,
                    onCellPrepared: function (e) {
                        if (e.rowType == "header" || e.rowType === "data") {
                            e.cellElement.addClass('moveToCenter');
                        }
                    },
                    columns: [
                        //{ dataField: 'BidId', caption: "BidId", visible: false, showInColumnChooser: false },
                        { dataField: "BidName", caption: "Bid Name", visible: true },
                        { dataField: 'BidDescription', caption: "Bid Description", wordWrapEnabled: true, visible: false, showInColumnChooser: true },
                        { dataField: "BidStatusDisplay", caption: "Bid Status", visible: true },
                        { dataField: "BidType", caption: "Bid Type", visible: false, showInColumnChooser: true, },
                        { dataField: 'Company', caption: "Company", visible: false, showInColumnChooser: true, },
                        { dataField: 'LaunchDate', caption: "Launch Date", visible: true, showInColumnChooser: true, dataType: 'date' },
                        { dataField: 'DueDate', caption: "Bid Due Date", visible: false, showInColumnChooser: true, dataType: 'date' },
                        {
                            dataField: 'CalculatedDueDate', caption: "Estimated Bid Due Date", visible: false, showInColumnChooser: true,
                            headerCellTemplate: function (header, info) {
                                $("<div>").html("<center>Estimated <br>Bid Due Date</center>").appendTo(header);
                            },
                        },
                        {
                            dataField: 'CurrentPhaseDueDate', caption: "Estimated Phase Due Date", dataType: 'date', visible: false, showInColumnChooser: true,
                            headerCellTemplate: function (header, info) {
                                $("<div>").html("<center>Estimated <br>Phase Due Date</center>").appendTo(header);
                            },
                        },

                        { dataField: 'CustNumber', caption: "Customer Number", visible: false, showInColumnChooser: true, },
                        { dataField: 'CustBranch', caption: "Customer Branch", visible: false, showInColumnChooser: true, },
                        { dataField: 'CustName', caption: "Customer Name", visible: false, showInColumnChooser: true, },
                        { dataField: 'CustCorpId', caption: "Customer Corp Id", visible: false, showInColumnChooser: true, },
                        {
                            dataField: 'CustCorpAccName', caption: "Customer Corp Account Name", visible: false, showInColumnChooser: true,
                            headerCellTemplate: function (header, info) {
                                $("<div>").html("<center>Customer Corp<br>Account Name</center>").appendTo(header);
                            },
                        },
                        { dataField: 'GroupId', caption: "Group Id", visible: false, showInColumnChooser: true, },
                        { dataField: 'GroupDesc', caption: "Group Description", visible: false, showInColumnChooser: true, },
                        { dataField: 'CreatedBy', caption: "Created By", visible: false, showInColumnChooser: true, },
                        { dataField: 'CreatedOn', caption: "Created On", visible: false, showInColumnChooser: true, },
                        {
                            dataField: 'CrossesFinalized', caption: "Crosses Finalized", visible: true, showInColumnChooser: true, headerCellTemplate: function (header, info) {
                                $("<div>").html("<center>Finalized<br/>Parts</center>").appendTo(header);
                            }
                        },
                        {
                            dataField: "CrossesReviewedBy", caption: "Crosses Reviewed By", visible: true, showInColumnChooser: true, wordWrapEnabled: true,
                            headerCellTemplate: function (header, info) {
                                $("<div>").html("<center>Crosses<br /> Reviewed By</center>").appendTo(header);
                            }
                        },
                        {
                            dataField: "CrossesNotReviewedBy", caption: "Crosses Not Reviewed By", visible: true, showInColumnChooser: true, wordWrapEnabled: true,
                            headerCellTemplate: function (header, info) {
                                $("<div>").html("<center>Crosses Not<br /> Reviewed By</center>").appendTo(header);
                            }
                        },
                        {
                            dataField: "InventoryReviewedBy", caption: "Inventory Reviewed By", visible: true, showInColumnChooser: true, wordWrapEnabled: true,
                            headerCellTemplate: function (header, info) {
                                $("<div>").html("<center>Inventory<br /> Reviewed By</center>").appendTo(header);
                            }
                        },
                         {
                             dataField: "InventoryNotReviewedBy", caption: "Inventory Not Reviewed By", visible: true, showInColumnChooser: true, wordWrapEnabled: true,
                             headerCellTemplate: function (header, info) {
                                 $("<div>").html("<center>Inventory Not<br /> Reviewed By</center>").appendTo(header);
                             }
                         },
                    ],
                });
            }
        });
    });
</script>