FleetPride.BidManager/Controllers/ReportsController.cs
using FleetPride.BidManager.Repository;
using FleetPride.BidManager.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FleetPride.BidManager.Controllers
{
    public class ReportsController : Controller
    {
        protected Utilities.Logger logger = new Utilities.Logger();

        IAuthorizationRepository _userInfoRepository;
        IReportsRepository _reportsRepository;

        /// <summary>  
        ///  Class Default constructor for instantiating the Repository Interfaces.
        /// </summary>
        public ReportsController(IAuthorizationRepository userInfoRepository, IReportsRepository reportsRepository)
        {
            _userInfoRepository = userInfoRepository;
            _reportsRepository = reportsRepository;
        }

        /// <summary>
        /// /
        /// </summary>
        /// <returns></returns>
        public ActionResult DataTeamReport()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.DataTeamReport))
            {
                if (Request.QueryString["BidId"] != null && Request.QueryString["BidName"] != null)
                {
                    int bidId = Convert.ToInt32(Request.QueryString["BidId"]);
                    string bidName = Convert.ToString(Request.QueryString["BidName"]);

                    ViewBag.BidName = bidName;
                    ViewBag.BidId = bidId;
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
                else
                {
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
            }
            else
            {
                return new HttpUnauthorizedResult();
            }
        }

        /// <summary>
        /// Default action method for Demand Team Report
        /// </summary>
        /// <returns></returns>
        public ActionResult DemandTeamReport()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.DemandTeamReport))
            {
                if (Request.QueryString["BidId"] != null && Request.QueryString["BidName"] != null)
                {
                    int bidId = Convert.ToInt32(Request.QueryString["BidId"]);
                    string bidName = Convert.ToString(Request.QueryString["BidName"]);

                    ViewBag.BidName = bidName;
                    ViewBag.BidId = bidId;
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
                else
                {
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
            }
            else
            {
                return new HttpUnauthorizedResult();
            }
        }

        /// <summary>
        /// Default action method for Demand Team Report
        /// </summary>
        /// <returns></returns>
        public ActionResult BidChangeReport()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.DemandTeamReport))
            {
                if (Request.QueryString["BidId"] != null && Request.QueryString["BidName"] != null)
                {
                    int bidId = Convert.ToInt32(Request.QueryString["BidId"]);
                    string bidName = Convert.ToString(Request.QueryString["BidName"]);

                    ViewBag.BidName = bidName;
                    ViewBag.BidId = bidId;
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
                else
                {
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
            }
            else
            {
                return new HttpUnauthorizedResult();
            }
        }

        public ActionResult InventoryReport()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.InventoryReport))
            {
                if (Request.QueryString["BidId"] != null && Request.QueryString["BidName"] != null)
                {
                    int bidId = Convert.ToInt32(Request.QueryString["BidId"]);
                    string bidName = Convert.ToString(Request.QueryString["BidName"]);

                    ViewBag.BidName = bidName;
                    ViewBag.BidId = bidId;
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
                else
                {
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
            }
            else
            {
                return new HttpUnauthorizedResult();
            }
        }

        /// <summary>
        /// Default action method for Bid Status Report
        /// </summary>
        /// <returns></returns>
        public ActionResult BidStatusReport()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.BidStatusReport))
            {
                ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                return View();
            }
            else
            {
                return new HttpUnauthorizedResult();
            }
        }

        public ActionResult BidStatusReportForDataTeam()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.BidStatusReportForDataTeam))
            {
                ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                return View();
            }
            else
            {
                return new HttpUnauthorizedResult();
            }
        }

        /// <summary>
        /// Get Demand Team Report Bids
        /// </summary>
        /// <returns></returns>
        public JsonResult DemandTeamReportBids()
        {
            var bidsList = _reportsRepository.DemandTeamReportBids(_userInfoRepository.GetAuthorisedUserRole(), System.Web.HttpContext.Current.User.Identity.Name);
            ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
            return new JsonResult()
            {
                Data = bidsList,
                MaxJsonLength = Int32.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult RevisePartsReport()
        {
            if (_userInfoRepository.HasAccess(Constants.Page.RevisePartsReport))
            {
                if (Request.QueryString["BidId"] != null )
                {
                    int bidId = Convert.ToInt32(Request.QueryString["BidId"]);
                    ViewBag.BidId = bidId;
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
                else
                {
                    ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();
                    return View();
                }
            }
            else
            {
                return new HttpUnauthorizedResult();
            }
        }
        public JsonResult RevisePartsBids()
        {
            var bidsList = _reportsRepository.RevisePartsBids(_userInfoRepository.GetAuthorisedUserRole(), System.Web.HttpContext.Current.User.Identity.Name);

            return new JsonResult()
            {
                Data = bidsList,
                MaxJsonLength = Int32.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult GetRevisePartsReport(int bidId)
        {
            var revisePartsReport = _reportsRepository.GetRevisePartsReport(bidId);
            ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();

            return new JsonResult()
            {
                Data = revisePartsReport,
                MaxJsonLength = Int32.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        /// <summary>
        /// Method to get demand team report
        /// </summary>
        /// <param name="bidId"></param>
        /// <returns></returns>
        public JsonResult GetDemandTeamReport(int bidId)
        {
            string approvalType = "Approved";
            var demandTeamReport = _reportsRepository.GetDemandTeamReport(bidId, approvalType, System.Web.HttpContext.Current.User.Identity.Name, _userInfoRepository.GetAuthorisedUserRole());
            ViewBag.Role = _userInfoRepository.GetAuthorisedUserRole();

            return new JsonResult()
            {
                Data = demandTeamReport,
                MaxJsonLength = Int32.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult LaunchBid(int bidId)
        {
            bool result = false;
            if (bidId <= 0)
            {
                result = false;
            }
            else
            {
                result = _reportsRepository.LaunchBid(bidId, System.Web.HttpContext.Current.User.Identity.Name);
            }

            return new JsonResult()
            {
                Data = result,
                MaxJsonLength = Int32.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        /// <summary>
        /// Method to get the Bid Status Report
        /// </summary>
        /// <param name="bidId"></param>
        /// <returns></returns>
        public JsonResult GetBidStatusReport()
        {
            var result = _reportsRepository.GetBidStatusReport(System.Web.HttpContext.Current.User.Identity.Name, _userInfoRepository.GetAuthorisedUserRole());

FleetPride.BidManager/Views/Reports/RevisePartsReport.cshtml
@using FleetPride.BidManager.Utilities;
@{
    ViewBag.Title = "Revised Parts Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <div class="container" style="width:auto !important">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1 style="float:left;">
                Revise Parts
            </h1>
            <div style="float:right;margin-top: 6px !important; font-weight:bold">
                <div id="dropDownBids" style="width:200px;display:inline-block;"></div>
            </div>
            <br /><br />
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="box box-default" id="box">
                <div class="box-body">
                    <div id="gridContainer"></div>
                </div>
            </div>
            <!-- /.box -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.container -->
</div>
<script type="text/javascript">
    var bidId;
    var bidName;
    var bidStatus;
    var bidType;
    var crossPartsInventoryData;
    var createdBy;
    var data;

    $(document).ready(function () {
        $("#nav_menu li").removeClass("active");
        $('#reports').addClass('active');
        $('#RevisePartsReport').addClass('active');
        $("#box").hide();
        var dataGrid;

        @if(ViewBag.bidId != null)
        {
           <text>bidId=</text>@ViewBag.BidId<text>;</text>
        }

        $("#spinner").show();
        $.ajax({
            url: "@Url.Action("RevisePartsBids", "Reports")",
            type: 'GET',
            contentType: 'application/json; charset=utf-8',
            success: function (bidList) {
                data = bidList;
                console.log(bidList);
                $("#spinner").hide();
                $("#dropDownBids").dxDropDownBox({
                    value: bidId,
                    width: 350,
                    valueExpr: "BidId",
                    placeholder: "Select Bid",
                    displayExpr: "BidName",
                    showClearButton: false,
                    dataSource: bidList,
                    contentTemplate: function (e) {
                        var value = e.component.option("value"),
                            $dataGrid = $("<div style='padding:0px' id='gridContainer_Bids' >").dxDataGrid({
                                dataSource: {
                                    store: {
                                        type: 'array',
                                        key: 'BidId',
                                        data: e.component.option("dataSource")
                                    }
                                },
                                columns: ["BidName"],
                                hoverStateEnabled: true,
                                filterRow: { visible: true },
                                scrolling: {
                                    mode: "virtual",
                                    showScrollbar: 'always'
                                },
                                height: 350,
                                selection: { mode: "single" },
                                selectedRowKeys: value,
                                showColumnHeaders: false,
                                onSelectionChanged: function (selectedItems) {
                                    var keys = selectedItems.selectedRowKeys;
                                    e.component.option("value", keys);
                                    e.component.close();
                                    bidId = keys[0];
                                    bidType = selectedItems.selectedRowsData[0].BidType;
                                    bidName = selectedItems.selectedRowsData[0].BidName;
                                    bidStatus = selectedItems.selectedRowsData[0].BidStatus;
                                    createdBy = selectedItems.selectedRowsData[0].CreatedBy;
                                    RevisePartsReport();
                                }
                            });
                        dataGrid = $dataGrid.dxDataGrid("instance");                      
                        return $dataGrid;
                    }
                });
            }
        });

        @if(ViewBag.bidId != null)
        {
            <text>
        bidId=</text>@ViewBag.bidId<text>;
        console.log(data);
            $.each(data, function( i ) {
            if(data[i].BidId == selectedBidId){
                bidName = data[i].BidName;
                }
            });
            RevisePartsReport();
            </text>
        }

        //function to load revise parts report
        function RevisePartsReport() {
            var userName = '@HttpContext.Current.User.Identity.Name';
            $("#box").show();
            $("#spinner").show();
            $.ajax({
                url: "@Url.Action("GetRevisePartsReport", "Reports")",
                type: 'POST',
                data: JSON.stringify({ bidId: bidId }),
                contentType: 'application/json; charset=utf-8',
                success: function (CrossPartsInventory) {
                    $("#spinner").hide();
                    crossPartsInventoryData = CrossPartsInventory;

                    dataGrid = $("#gridContainer").dxDataGrid({
                        dataSource: CrossPartsInventory,
                        paging: {
                            pageSize: 50
                        },
                        height: function () {
                            return dynamicheight = $(document).height() - 190;
                        },
                        pager: {
                            showPageSizeSelector: true,
                            allowedPageSizes: [10, 50, 100, 200, 500],
                            showInfo: true
                        },
                        "export": {
                            enabled: true,
                            fileName: "InventoryUpdate_PartsWon_List" + "_" + '@DateTime.Now.ToString("MM/dd/yyyy HH:mm:ss")',
                        },
                        filterRow: {
                            visible: true,
                            applyFilter: "auto"
                        },
                        headerFilter: {
                            visible: true
                        },
                        scrolling: {
                            showScrollbar: 'always'
                        },
                        columnChooser: {
                            enabled: true,
                            height: 360,
                            width: 250,
                            mode: "select",
                            emptyPanelText: 'Place to hide the columns.'
                        },                        
                        hoverStateEnabled: true,
                        allowColumnResizing: true,
                        columnAutoWidth: true,
                        showBorders: true,
                        showColumnLines: true,
                        showRowLines: true,
                        allowColumnReordering: true,
                        columns: [
                            { dataField: "BidPartId", caption: "BidPartId", dataType: 'number', visible: false, showInColumnChooser: false, allowEditing: false },
                            { dataField: "CrossPartId", caption: "CrossPartId", dataType: 'number', visible: false, showInColumnChooser: false, allowEditing: false },
                            { dataField: "CrossPartInventoryId", caption: "CrosssPartInventoryId", dataType: 'number', visible: false, showInColumnChooser: false, allowEditing: false },
                            { dataField: "CustomerPartNumber", caption: "Customer Part Number", allowEditing: false, visible: true, dataType: 'number', fixed: true,
                                headerCellTemplate: function (header, info) {
                                    $("<div>").html("<center>Customer<br> Part Number</center>").appendTo(header);
                                },
                            },
                            { dataField: "ManufacturerPartNumber", caption: "Manufacturer Part Number", allowEditing: false, visible: true,
                                headerCellTemplate: function (header, info) {
                                    $("<div>").html("<center>Manufacturer<br> Part Number</center>").appendTo(header);
                                },
                            },
                            { dataField: 'PartDescription', caption: "Customer Part Description", wordWrapEnabled: true, allowEditing: false, visible: true,
                                headerCellTemplate: function (header, info) {
                                    $("<div>").html("<center>Customer<br>Part<br> Description</center>").appendTo(header);
                                },
                            },

                            { dataField: "CrossPoolNumber", caption: "Cross Pool", allowEditing: false, visible: false, dataType: 'number',},
                            { dataField: "CrossPartNumber", caption: "Cross Part No", allowEditing: false, visible: false, },
                            { dataField: 'CrossPartDescription', caption: "Cross Part Description", wordWrapEnabled: true, allowEditing: false, visible: false,
                                headerCellTemplate: function (header, info) {
                                    $("<div>").html("<center>FP Part<br> Description</center>").appendTo(header);
                                },
                            },
                            
                            { dataField: "CrossPrice", caption: "Price", allowEditing: false, visible: false, dataType: 'number', visible: false},

                            { dataField: "CrossICOST", caption: "ICOST", allowEditing: false, visible: false, showInColumnChooser: true, dataType: 'number',},

                            { dataField: "NewPool", caption: "FP Pool", allowEditing: false, visible: true, showInColumnChooser: true, dataType: 'number', },
                            { dataField: "NewPartNo", caption: "FP Part No", allowEditing: false, visible: true, showInColumnChooser: true, },
                            
                            { dataField: "RevisedPool", caption: "Revised Pool", allowEditing: false, visible: true, dataType: 'number',},
                            { dataField: "RevisedPartNumber", caption: "Revised Part No", allowEditing: false, visible: true, },

                            { dataField: "NewPrice", caption: "New Price", allowEditing: false, visible: false, showInColumnChooser: true, dataType: 'number',},

                            { dataField: "Location", caption: "Location", allowEditing: false, visible: true, dataType: "string" },
                            { dataField: "EstimatedAnnualUsage", caption: "Estimated Annual Usage", allowEditing: false, visible: false, showInColumnChooser: true, dataType: 'number', validationRules: [{ type: 'required', trim: true }],
                                headerCellTemplate: function (header, info) {
                                    $("<div>").html("<center>Estimated<br> Annual Usage</center>").appendTo(header);
                                },
                            },
                            { dataField: "CustPartUOM", caption: "Cust Part UOM", allowEditing: false, visible: false, showInColumnChooser: true, dataType: 'number',
                                headerCellTemplate: function (header, info) {
                                    $("<div>").html("<center>Cust Part<br> UOM</center>").appendTo(header);
                                },
                            },
                            { dataField: "StockingType", caption: "Stocking Type", allowEditing: false, visible: true,
                                headerCellTemplate: function (header, info) {
                                    $("<div>").html("<center>Stocking<br>Type</center>").appendTo(header);
                                },
                            },
                             { dataField: "RevisePartComments", caption: "Comments", allowEditing: false, visible: true,
                                 headerCellTemplate: function (header, info) {
                                     $("<div>").html("<center>Comments</center>").appendTo(header);
                                 },
                             },

                        ],

                        onCellPrepared: function (e) {
                            if (e.rowType == "header" || e.rowType === "data") {
                                e.cellElement.addClass('moveToCenter');
                            }
                        }

                    });
                }
            });
        }
    });


</script>